#
#                          Building aestxyz-dockerio
#
# Adjoin docker.io
#
FROM paracamplus/aestxyz_cpan
MAINTAINER ChristianQueinnec "christian.queinnec@paracamplus.com"
ENV HOSTNAME whatever.paracamplus.net

WORKDIR /root/

RUN bash -c 'wget -qO- https://get.docker.io/ | sh'

#end.
