--- 
# Configuration of a Docker container running a Marking Driver Daemon
# on Bijou and using another (external) container running a Marking
# Slave. It uses the real database.
# 
#
# Static unmodifiable files are stored in /opt/vmmdr.paracamplus.com
# Files needed to run MD are in /home/md/ This directory may be safely erased
#   to reconfigure the MD. 
# Static libraries for the MD and MS are in /home/fw4ex
# ATTENTION: ownership and rights to check and fix!!
# and still some unused directories?

# *.paracamplus.com sont les serveurs globaux de la constellation

# Descriptive:
configname: VMmdr
version: 1242
tmpdir:  /home/md/tmp
pidfile: /home/md/md.pid
rngschemafile: /opt/vmmdr.paracamplus.com/fw4ex.rng
privateKeyFile: /home/fw4ex/.ssh/fw4excookie.insecure.key

# This loggerConfiguration will be written in loggerconf:
loggerConfiguration: |
    log4perl.logger = DEBUG, MDLogFile
    log4perl.appender.Screen = Log::Log4perl::Appender::Screen
    log4perl.appender.Screen.layout = Log::Log4perl::Layout::SimpleLayout
    log4perl.appender.MDLogFile = Log::Log4perl::Appender::File
    log4perl.appender.MDLogFile.filename = /var/log/fw4ex/md/md.log
    log4perl.appender.MDLogFile.layout = Log::Log4perl::Layout::PatternLayout
    log4perl.appender.MDLogFile.layout.ConversionPattern=%d %-5p - %m%n
loggerconf: /home/md/md-log4perl.conf

# When test is true, VMmd will run without polling Internet nor
# storing results on remote servers. May also be set with 
# qnc-fw4ex.sh start -test
#test: 1

scheduler:
    class: Paracamplus::FW4EX::MD_smartShufflingRoundRobinScheduler
    # sleep time before asking remote servers for jobs or exercises.
    sleeptime: 10
    batchFrequency: 3
    test_pluginConfigs:
       - class: Paracamplus::FW4EX::MD_plugin::CleanSpace::ByPercentage
         period: 301
         directory: /home/md/
         maxpercentage: 80
         action: /opt/vmmdr.paracamplus.com/Scripts/cleanHomeMD.sh
       - class: Paracamplus::FW4EX::MD_plugin::CleanSpace::BySize
         period: 361
         directory: /var/log/fw4ex/
         maxsize: 100M
         action: /opt/vmmdr.paracamplus.com/Scripts/cleanVarLogFW4EX.sh
    pluginConfigs:
# FUTURE: should try first to save in the remote db and, if not
# possible, in the local database:
       - class: Paracamplus::FW4EX::MD_plugin::TransmitMarks
         verbose: 6
         rdbclass: Paracamplus::FW4EX::Schema::RFW4EXDB
         rdbhost: db.paracamplus.com
         rdbname: fw4ex
         rdbport: 55432
         rdbuser: fw4exmd
         rdbpassword: du73vxYDj
         ldbclass: Paracamplus::FW4EX::Schema::LFW4EXDB
         ldbname: fw4ex
         ldbport: 5432
         ldbuser: transmitter
         ldbpassword: Glyrywel3
         tunneluser: saver
         tunneluserkey: saver_dsa
#
# On sauve systematiquement sur s.paracamplus.com Il faut que sur
# s.paracamplus.com, les repertoires [bes] appartiennent a fw4ex:fw4ex.
       - class: Paracamplus::FW4EX::MD_plugin::TransmitReports
         server: s.paracamplus.com
         destination: /var/www/s.paracamplus.com/
         username: fw4ex
         privateKeyFile: /home/fw4ex/.ssh/fw4ex
         period: 0
         recountperiod: 30
         rsyncFlags: --ignore-existing
         sources:
            - /var/www/s.paracamplus.com/s
            - /var/www/s.paracamplus.com/b
            - /var/www/s.paracamplus.com/e

       - class: Paracamplus::FW4EX::MD_plugin::CleanSpace::ByPercentage
         period: 51
         directory: /home/md/
         maxpercentage: 75
         action: /opt/vmmdr.paracamplus.com/Scripts/cleanHomeMD.sh
#
       - class: Paracamplus::FW4EX::MD_plugin::CleanSpace::ByPercentage
         period: 59
         directory: /opt/
         maxpercentage: 90
         action: /opt/vmmdr.paracamplus.com/Scripts/cleanOpt.sh
#
       - class: Paracamplus::FW4EX::MD_plugin::CleanSpace::BySize
         period: 3601
         directory: /var/log/fw4ex/
         maxsize: 100M
         action: /opt/vmmdr.paracamplus.com/Scripts/cleanVarLogFW4EX.sh

# ATTENTION, les machines citees doivent apparaitre dans les
# known_hosts de root et de fw4ex et, bien sur, dans les
# authorized_keys des serveurs distants.

# Administrative cookie to use when polling A and E servers:
# Attention: for VMmd, admin is also author!
aAdminName: 42


# Which A server to poll for students' jobs or batches:
aServerURLs:
     - file:///tmp/incoming/jobs
     - http://a.paracamplus.com
test_aServerURLs:
     - file:///tmp/incoming/jobs


# Which E server to poll for incoming authors' exercices to autocheck:
eServerURLs:
     - file:///tmp/incoming/exercises
     - http://e.paracamplus.com
test_eServerURLs:
     - file:///tmp/incoming/exercises
incomingExerciseDir: /home/md/incoming

# Base locale
db:
    class: Paracamplus::FW4EX::Schema::FW4EXDB
    dsn: dbi:Pg:dbname=fw4ex host=localhost port=5432
    dbname: fw4ex
    dbport: 5432
    dbuser: fw4exmd
    dbpassword: du73vxYDj


markEngine:
    class: Paracamplus::FW4EX::SimplisticMarkEngine
    version: 1242
    jobDir:      /home/md/cache/jobs.d
    resultsDir:  /home/md/results
    exerciseDir: /home/md/autocheck
    tmpDir:      /home/md/tmp
    binDir:      /home/fw4ex/bin
    rngschemafile:    /opt/vmmdr.paracamplus.com/fw4ex.rng
    private_key_file: /home/fw4ex/.ssh/fw4excookie.insecure.key
#   sleeptime: 5

    # These directories are within the marking slave:
    vmCommonLib:
        fw4exlib:     /home/fw4ex/fw4exlib
        fw4exrootlib: /root/fw4exrootlib
        # Leave /tmp/ empty for students so use /home/md instead.
        # Configure /root/fw4exrootlib/config.sh and /home/fw4ex/config.sh:
        exports:
          JOB_DIR:                /home/md/cache/jobs.d
          USE_EXERCISE_CACHE:     true
          EXERCISE_CACHE_DIR:     /home/md/cache/exercises.d
          EXERCISE_CACHE_TIMEOUT: 3000
          AUTHORS_MAX_NUMBER:     99
          STUDENTS_MAX_NUMBER:    99
          SPACE_THRESHOLD:        65            
          AUTHOR_MAXCPU:          90
          AUTHOR_MAXOUT:          500$k
          AUTHOR_MAXERR:          100$k
          DEBUG_VERBOSITY:        0
          # Should also set confineAuthor.sh!!!!!!!!!!! FUTURE

    # Version with an external Marking Slave:
    vmname: Paracamplus::FW4EX::VM::MSbySSH
    Paracamplus::FW4EX::VM::MSbySSH:
#        ip: 127.0.0.1
#        port: 58022
        ip: vmms.paracamplus.com
        port: 22
        keydir: /home/fw4ex/.ssh
        keyprefix: vmms_rsa

    exerciseFetcher:
# version pour exercices distants (ce qui permet d'envoyer de nouveaux
# exercices a la VM via le protocole http normal).
        class: Paracamplus::FW4EX::ExerciseFetcherLWP
        exerciseDir: /home/md/cache/exercises.d
        eServerUrl: http://e.paracamplus.com
        seServerUrl: http://e.paracamplus.com
        private_key_file: /home/fw4ex/.ssh/fw4excookie.insecure.key
        eAdminName: 42
    test_exerciseFetcher:
        class: Paracamplus::FW4EX::ExerciseFetcherLWP
        exerciseDir: /home/md/cache/exercises.d
        eServerUrl: http://e.paracamplus.com
        seServerUrl: http://e1.paracamplus.com
        private_key_file: /home/fw4ex/.ssh/fw4excookie.insecure.key
        eAdminName: 42

storeEngine:
      class: Paracamplus::FW4EX::LocalStoreEngine
# Stockage direct interne sur VMmd:
      storageDir:          /var/www/s.paracamplus.com/s
      batchStorageDir:     /var/www/s.paracamplus.com/b
      autocheckStorageDir: /var/www/s.paracamplus.com/e
# Attention, les rapports sont stockes par MD donc avec fw4ex:fw4ex comme 
# proprietaire. Il faut qu'ils soient lisibles par apache qui tourne
# le serveur s. Les rapports sont stockes en local mais un greffon de
# l'ordonnanceur les copie sur s1 et s3.
#      postCommand: /opt/vmmdr.paracamplus.com/Scripts/hackJobResult.sh

#end.
